# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_cn', models.CharField(max_length=30, verbose_name='中文名')),
                ('country_en', models.CharField(max_length=30, verbose_name='英文名')),
                ('letter2', models.CharField(max_length=2, verbose_name='二位英文代码')),
                ('letter3', models.CharField(max_length=3, verbose_name='三位英文代码')),
                ('digital_code', models.CharField(max_length=5, verbose_name='数字代码')),
                ('ISO_3166_2_code', models.CharField(max_length=30, verbose_name='ISO-3166-2标准代码')),
            ],
            options={
                'verbose_name': '国家地区信息表',
                'verbose_name_plural': '国家地区信息表',
            },
        ),
    ]
