# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryinfo',
            name='ISO_3166_2_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ISO-3166-2标准代码'),
        ),
        migrations.AlterField(
            model_name='countryinfo',
            name='letter3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='三位英文代码'),
        ),
    ]
