# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanBase', '0002_auto_20180116_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_section', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ip段')),
                ('ip_start', models.GenericIPAddressField(blank=True, null=True, verbose_name='开始ip')),
                ('ip_end', models.GenericIPAddressField(blank=True, null=True, verbose_name='结束ip')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='总量')),
                ('deal_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanBase.CountryInfo', verbose_name='所属国家')),
            ],
            options={
                'verbose_name_plural': 'ip段信息',
                'verbose_name': 'ip段信息',
            },
        ),
    ]
