# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanBase', '0003_ipsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('deal_time', models.DateTimeField(blank=True, null=True, verbose_name='扫描时间')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanBase.CountryInfo', verbose_name='所属国家')),
            ],
            options={
                'verbose_name': 'ip信息',
                'verbose_name_plural': 'ip信息',
            },
        ),
        migrations.RemoveField(
            model_name='ipsection',
            name='ip_end',
        ),
        migrations.RemoveField(
            model_name='ipsection',
            name='ip_start',
        ),
        migrations.AddField(
            model_name='ipsection',
            name='netmask',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='广播地址'),
        ),
        migrations.AddField(
            model_name='ipsection',
            name='network',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='网关地址'),
        ),
        migrations.AddField(
            model_name='ipinfo',
            name='iP_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanBase.IPSection', verbose_name='所属ip段'),
        ),
    ]
