# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanBase', '0004_auto_20180116_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipinfo',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='ip'),
        ),
    ]
